INSERT INTO public.lots (title, short_description, description, image_url, initial_bid, current_bid, bids_count, ends_at, status)
VALUES
('Caminhão Scania R440 6x2', 'Caminhão em excelente estado, ideal para transporte de cargas pesadas.', 'Detalhes completos do caminhão Scania R440 6x2, incluindo histórico de manutenção, quilometragem e inspeções recentes. Perfeito para frotas ou autônomos que buscam um veículo robusto e confiável. Documentação em dia e pronto para transferência.', 'https://picsum.photos/seed/scania/800/600', 150000.00, 155000.00, 5, NOW() + INTERVAL '7 days', 'aberto'),
('Trator Agrícola John Deere 6100J', 'Trator potente e versátil para diversas operações agrícolas.', 'Este trator John Deere 6100J é uma máquina agrícola de alta performance, ideal para preparo de solo, plantio e colheita. Equipado com tecnologia de ponta para otimizar o trabalho no campo. Manutenção preventiva realizada e em ótimas condições de uso.', 'https://picsum.photos/seed/johndeere/800/600', 120000.00, 122500.00, 3, NOW() + INTERVAL '5 days', 'aberto'),
('Retroescavadeira Caterpillar 416F2', 'Equipamento robusto para construção civil e terraplanagem.', 'Retroescavadeira Caterpillar 416F2, ano 2018, com poucas horas de uso. Ideal para projetos de construção, escavação e movimentação de terra. Manutenção em dia, pneus em bom estado e pronta para trabalhar. Acompanha caçamba padrão.', 'https://picsum.photos/seed/caterpillar/800/600', 180000.00, 180000.00, 0, NOW() + INTERVAL '10 days', 'aberto'),
('Carroceria Graneleira 12m', 'Carroceria para caminhão, em bom estado de conservação.', 'Carroceria graneleira de 12 metros de comprimento, ideal para transporte de grãos e outros materiais a granel. Estrutura reforçada, assoalho em bom estado. Pronta para ser instalada em caminhões compatíveis. Pequenos reparos estéticos podem ser necessários.', 'https://picsum.photos/seed/carroceria/800/600', 25000.00, 25000.00, 0, NOW() + INTERVAL '3 days', 'aberto'),
('Lote de Sucata Metálica', 'Diversos tipos de sucata ferrosa e não ferrosa.', 'Lote composto por aproximadamente 5 toneladas de sucata metálica mista, incluindo ferro, aço e alguns metais não ferrosos. Ideal para reciclagem. O comprador é responsável pela retirada e transporte do material.', 'https://picsum.photos/seed/sucata/800/600', 5000.00, 5000.00, 0, NOW() + INTERVAL '2 days', 'aberto'),
('Máquina de Solda Industrial', 'Máquina de solda de alta potência para uso industrial.', 'Máquina de solda MIG/MAG industrial, 400A, em perfeito funcionamento. Ideal para serralherias, indústrias metalúrgicas e oficinas de grande porte. Acompanha tocha e cabos. Revisada recentemente.', 'https://picsum.photos/seed/solda/800/600', 8000.00, 8000.00, 0, NOW() + INTERVAL '6 days', 'aberto'),
('Empilhadeira Hyster 3.0T', 'Empilhadeira a diesel, capacidade de 3 toneladas.', 'Empilhadeira Hyster, modelo H3.0FT, a diesel, capacidade de carga de 3.000 kg. Torre duplex, pneus sólidos. Ideal para movimentação de cargas em armazéns e pátios. Manutenção em dia e pronta para uso.', 'https://picsum.photos/seed/empilhadeira/800/600', 45000.00, 45000.00, 0, NOW() + INTERVAL '8 days', 'aberto'),
('Gerador de Energia a Diesel 100 kVA', 'Gerador de energia para uso comercial ou industrial.', 'Gerador de energia a diesel, 100 kVA, motor Cummins. Ideal para backup de energia em indústrias, hospitais ou eventos. Baixas horas de uso, manutenção preventiva realizada. Acompanha painel de controle.', 'https://picsum.photos/seed/gerador/800/600', 60000.00, 60000.00, 0, NOW() + INTERVAL '4 days', 'aberto');